site_name : Graphical models documentation

repo_url: https://github.com/math-stat/python-project-template

theme:
  name: material
  locale: en

extra:
    version:
        default: latest
        provider: mike

plugins:
    - mkdocstrings
    - mike:
        canonical_version: latest

nav:
  - index.md
  - reference.md
